[phases.setup]
nixPkgs = ["php82", "php82Packages.composer", "nodejs_22", "npm-9_x", "libmysqlclient"]

[phases.install]
cmds = [
    "mkdir -p bootstrap/cache storage/framework/views storage/framework/sessions storage/framework/cache storage/app/public",
    "chmod -R 777 bootstrap/cache storage",
    "composer install --ignore-platform-reqs --no-interaction --prefer-dist",
    "rm -rf package-lock.json node_modules",
    "npm install"
]

[start]
cmd = "mkdir -p storage/framework/views storage/framework/sessions storage/framework/cache storage/app/public bootstrap/cache && chmod -R 777 storage bootstrap/cache && php artisan optimize:clear && php artisan migrate --force && php artisan storage:link && php artisan serve --host=0.0.0.0 --port=$PORT"

