
[phases.install]
cmds = [
    "mkdir -p bootstrap/cache storage/framework/views storage/framework/sessions storage/framework/cache storage/app/public",
    "chmod -R 777 bootstrap/cache storage",
    "npm install"
]

[phases.build]
cmds = [
    "npm run build",
    "php artisan optimize:clear"
]

